export const GET_ACCOUNTS_PENDING = 'GET_ACCOUNTS_PENDING';
export const GET_ACCOUNTS_FAILED = 'GET_ACCOUNTS_FAILED';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
